name: CI

on:
  push:
    branches: ["main"]
    paths: "kristoffer.is/**"
  pull_request:
    paths: "kristoffer.is/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kristoffer.is

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.x

      - name: Install
        run: yarn

      - name: Lint
        run: yarn workspaces run lint

      - name: Typecheck
        run: yarn workspaces run typecheck

      - name: Build
        run: yarn workspaces run build
