name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run-script lint --workspaces --if-present

      - name: Test
        run: npm run-script test --workspaces --if-present

      - name: Typecheck
        run: npm run-script typecheck --workspaces --if-present

      - name: Build
        run: npm run-script build --workspaces --if-present
