name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.x

      - name: Install
        run: yarn

      - name: Lint
        run: yarn workspaces run lint

      - name: Typecheck
        run: yarn workspaces run typecheck

      - name: Build
        run: yarn workspaces run build
