name: CI

on:
  push:
    branches: [master]
    # paths: "kristoffer.is/*"
  pull_request:
    branches: [master]
    # paths: "kristoffer.is/*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: kristoffer.is

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x

      - name: Install
        run: yarn

  check:
    needs: [setup]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kristoffer.is

      - name: Lint
        run: yarn workspaces run lint

      - name: Typecheck
        run: yarn workspaces run typecheck

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kristoffer.is

      - name: Build
        run: yarn workspaces run build
